config/routes.rb
Rails.application.routes.draw do
  resources :receipts
  resources :records, only: [:index, :show, :create, :destroy]
  resources :line_items
  resources :carts
  resources :posts
  root 'pages#home', as: 'home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    belongs_to :user

    def add_post(post_id)
        current_item = line_items.find_by_post_id(post_id)
        if current_item
            current_item.quantity += 1
        else
            current_item = line_items.build(post_id: post_id)
        end
        current_item
    end

    def total_price 
        line_items.to_a.sum { |item| item.total_price }
    end

    def total_cost 
        line_items.to_a.sum { |item| item.total_cost }
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /carts
  # GET /carts.json
  def index
    @carts = current_user.carts
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find_by(id: params[:id])
    unless current_user == @cart.user
      redirect_to posts_path
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.line_items.each do |a|
      temp = a.quantity
      post = Post.find(a.post_id)
      post.quantity +=temp
      post.save
    end
    
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<!--
<h2>Your cart</h2>
<table>
<tr class="total_line">
      <td colspan="2">Total Price</td>
      <td class="total_cell"><%= @cart.total_price %> VNĐ</td>
  </tr>
  <tr class="total_line">
      <td colspan="2">Total Cost</td>
      <td class="total_cell"><%= @cart.total_cost %> VNĐ</td>
  </tr>
</table>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Price</th>
      <th>Cost</th>
      <th>Quantity</th>
      <th>In Stock</th>
      <th>Total Price</th>
      <th>Total Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart.line_items.each do |a| %>
      <tr>
        <td><%= a.post.title %></td>
        <td><%= a.post.body %></td>
        <td><%= a.post.price %> VNĐ</td>
        <td><%= a.post.cost %> VNĐ</td>
        <td><%= a.quantity %></td>
        <td><%= a.post.quantity %></td>
        <td class="item_price"><%= a.total_price %> VNĐ</td>
        <td class="item_price"><%= a.total_cost %> VNĐ</td>
        <td><%= link_to 'Edit', edit_line_item_path(a) %></td>
        <td><%= link_to 'Delete', a, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= button_to 'Empty Cart', cart, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= button_to 'Sold', receipts_path, method: :post, data: { confirm: 'Are you sure?' } %>
<div-->

	
	<div class="row col-12" id="size">
		<div class="col-9" id="displayproducts">
			<div class="jumbotron" id="jumbotronproduct1">
					<div class="container-fluid">
						<!-- Đơn hàng 1-->
						<% @cart.line_items.each do |a| %>
						<div class="row col-12" id="product1">
					  		<div class="row col-6">
						    	<div class="col-1 text-left" id="productnumerical">
						    		<p></p>
								</div>
								<div class="col-1 text-left" id="productdelete">
						    		<span class="fa fa-trash-o"></span>
								</div>
								<div class="row col-4 text-left" id="productid">
						    		<p><%= a.post.title %></p>
								</div>
								<div class="row col-6 text-left" id="productname">
						    		<p><%= a.post.body %></p>
								</div>
							</div>

							<div class="row col-6">
						    	<div class="col-2 text-right" id="productquantity">
						    		<p><%= a.quantity %></p>
								</div>
								<div class="col-5 text-right" id="productprice">
						    		<p><%= a.total_price %></p>
								</div>
								<div class="col-5 text-right" id="producttotal">
						    		<b><%= a.total_cost %></b>
								</div>
							</div>
						</div>
						<% end %>
					</div>
				</div>
		</div>	
				
		<div class="col-3" id="purchase">
			<div style="/*background:transparent !important*/" class="jumpbotron-fluid" id="colorbill">
				<div class="container-fluid" id="colorbillpart">
				<div class="row col-12">
					<div class="col-8" id="col8">
						<div class="dropdown">
						  <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
						  	<span class="fa fa-user-circle"></span>
						    Họ tên nhân viên 
						  </button>
						  <div class="dropdown-menu">
						    <a class="dropdown-item" href="#">Nhân viên 1</a>
						    <a class="dropdown-item" href="#">Nhân viên 2</a>
						    <a class="dropdown-item" href="#">Nhân viên 3</a>
						  </div>
						</div>
					</div>
					<div class="col-4">
						
					</div>
				</div>
				<div class="row col-12">
					<form class="form-inline">
						<input type="search" class="form-control" size="48" placeholder="Tìm sản phẩm" required>
					</form>
				</div>
				<div class="row col-12">
					<div class="dropdown">
					  <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
					  	<span class="fa fa-money"></span>
					    Bảng giá chung 
					  </button>
					  <div class="dropdown-menu">
					    <a class="dropdown-item" href="#">Giá chung 1</a>
					    <a class="dropdown-item" href="#">Giá chung 2</a>
					    <a class="dropdown-item" href="#">Giá chung 3</a>
					  </div>
					</div>
				</div>
				<div class="row col-12">
					<ul class="nav nav-tabs">
					  <li class="nav-item">
					    <a class="nav-link" href="#">Hóa đơn</a>
					  </li>
					</ul>
					<!--div class="tab">
  						<button class="tablinks" id="billbutton">Hóa đơn</button>
					</div>
					<hr style="height:1px;border-width:0;color:gray;background-color:gray"-->
				</div>
				<div id="invoice">
					<div class="row col-12">
						<div class="col-6">
							<p>Tổng tiền hàng</p>
						</div>
						<div class="col-6 text-right">
							<p><%= @cart.total_price %></p>
						</div>
					</div>
					<div class="row col-12">
						<div class="col-6">
							<p>Giảm giá</p>
						</div>
						<div class="col-6 text-right">
							<p>0</p>
						</div>
					</div>
					<div class="row col-12">
						<div class="col-6">
							<p><b>Khách cần trả</b></p>
						</div>
						<div class="col-6 text-right">
							<p><%= @cart.total_price %></p>
						</div>
					</div>
					<div class="row col-12">
						<div class="col-6">
							<p>Tiền thừa trả khách</p>
						</div>
						<div class="col-6 text-right">
							<p>0</p>
						</div>
					</div>
				</div>
				<ul class="navbar-nav" id="invoice">
				</ul>
				<div class="row col-12" id="notice">
					<form class="form-inline">
						<!--span class="fa fa-pencil"></span-->
						<input type="search" class="form-control" size="48" placeholder="✏ Ghi chú" required>
					</form>
				</div>
				<div class="row col-12">
					<%= button_to 'Thanh toán', receipts_path, method: :post, data: { confirm: 'Are you sure?' }, type: 'button', class: 'btn btn-info col-lg-12', id: 'purchasebutton' %>
					<%= button_to 'Xóa', cart, method: :delete, data: { confirm: 'Are you sure?' }, type: 'button', class: 'btn btn-danger col-lg-12', id: 'purchasebutton' %>
				</div>
				<div class="row col-12" id="supportcustomer">
					<span class="fa fa-phone"></span>
					<p class="font-italic"> Hỗ trợ khách hàng 1800 1234</p>	
				</div>

			</div>


		</div>
		</div>
	</div>
	<!--script type="text/javascript"></script-->
	
</body>
</html>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @cart %>