config/routes.rb
Rails.application.routes.draw do
  resources :receipts
  resources :records, only: [:index, :show, :create, :destroy]
  resources :line_items
  resources :carts
  resources :posts
  root 'pages#home', as: 'home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    before_destroy :check_if_has_line_item
    validate :check_if_price_and_cost
    validates :title, :body, :price, :cost, :quantity, presence: true
    validates :price, numericality: {greater_than_or_equal_to: 1000}
    validates :cost, numericality: {greater_than_or_equal_to: 1000}
    validates :quantity, numericality: {greater_than_or_equal_to: 0}
    validates :title, uniqueness: {scope: :user_id}
    has_many :line_items, dependent: :destroy
    has_one_attached :image, dependent: false
  
    def self.search(search)
        if search
            where('body LIKE ? OR title LIKE ?', "%#{search}%", "%#{search}%")
        else
            all
        end
    end

private
    def check_if_has_line_item
        if line_items.any?
            errors.add(:base, 'This product has a LineItem')
            throw(:abort)
        end
    end

    def check_if_price_and_cost
        errors.add(:cost, "cost can't be larger than price") unless price > cost
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.posts.search(params[:search]).order(sort_column + " " + sort_direction)
    @cart = current_cart
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by(id: params[:id])
    unless current_user == @post.user
      redirect_to posts_path
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :price, :cost, :quantity, :image)
    end

    def sort_column
      Post.column_names.include?(params[:sort]) ? params[:sort] : "title"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction])? params[:direction] : "asc"
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<!--
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
-->

<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div id="info" class="container tab-pane active"><br>
              <div id="chart" style="">
                <div class="row-12">
                  <div class="col-10">
                    <form>
                      <div class="form-group row">
                        <div><%= form.label :title, "Mã hàng", class: "col-*-4", style: "margin-left: 15px;"%></div>
                        <div class="col-*-8" style="margin-left: 63px;">
                          <%= form.text_field :title, class: "form-control", id: "infobar" %>
                        </div>
                      </div>
                      <div class="form-group row">
                        <div><%= form.label :body, "Tên hàng",class: "col-*-4", style: "margin-left: 15px;" %></div>
                        <div class="col-*-8" style="margin-left: 63px;">
                          <%= form.text_field :body, class: "form-control", id: "infobar" %>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label><%= form.label :cost, "Giá vốn", class: "col-*-4", style: "margin-left: 15px;" %></label>
                        <div class="col-*-8" style="margin-left: 68px;">
                          <%= form.number_field :cost, class: "form-control", id: "infobar" %>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label><%= form.label :price, "Giá bán", class: "col-*-4", style: "margin-left: 15px;" %></label>
                        <div class="col-*-8" style="margin-left: 68px;">
                          <%= form.number_field :price, class: "form-control", id:"infobar"  %>
                        </div>
                      </div>
                      <div class="form-group row">
                        <div><%= form.label :quantity, "Số lượng",class: "col-*-4", style: "margin-left: 15px;" %></div>
                        <div class="col-*-8" style="margin-left: 60px;">
                          <%= form.number_field :quantity, class: "form-control", id: "infobar" %>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label><%= form.label :image, "Ảnh",class: "col-*-4", style: "margin-left: 15px;" %></label>
                        <div class="col-*-8" style="margin-left: 90px;">
                          <form>
                            <div class="custom-file">
                              <input >
                              <%= form.file_field :image, class: "custom-file-input", id: "customFile", style: "width: 400px;" %>
                              <label class="custom-file-label" for="customFile">Choose file</label>
                            </div>
                          </form>
                        </div>
                      </div>
                  </form>
                </div>

                <div class="col-3">
                </div>
              </div>
              <%= button_tag(type: 'submit', class: "btn btn-success", id: "searchbutton", style: "margin-bottom: 20px; margin-left: 835px !important;") do %>
              <span class="fa fa-floppy-o"></span> Lưu
              <% end %>
              <% end %>

  <script>
  $(document).ready(function(){
    $(".nav-tabs a").click(function(){
      $(this).tab('show');
    });
  });
</script>
<script>
function myFunction() {
  // Declare variables
  var input, filter, ul, li, a, i, txtValue;
  input = document.getElementById('myInput');
  filter = input.value.toUpperCase();
  ul = document.getElementById("myUL");
  li = ul.getElementsByTagName('li');

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    a = li[i].getElementsByTagName("a")[0];
    txtValue = a.textContent || a.innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>

<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>
</body>
</html>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang = "en">
<head>
	<meta charset="utf-8">
  <title>TuanMinh</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
  <link href="./css/style_product.css" rel="stylesheet">
  <link href="https://fonts.google.com/specimen/PT+Sans?sidebar.open&selection.family=PT+Sans:wght@700" rel="stylesheet"></link>
</head>
<body>
	<!--Navigation-->
  <div class="row col-12" id="position">
    <div class="col-2" id="searchproduct">
        <div style="/*background:transparent !important*/" class="jumpbotron-fluid" id="color">

            <h2 id="hanghoa">Hàng hóa</h2>
            <b id="type">Nhóm hàng</b>
            <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Tìm kiếm nhóm hàng">

            <ul id="myUL">
              <li><a href="#">Nhóm hàng 011</a></li>
              <li><a href="#">Nhóm hàng 012</a></li>
              <li><a href="#">Nhóm hàng 021</a></li>
              <li><a href="#">Nhóm hàng 022</a></li>
            </ul>
        </div>
    </div>


    <div class="col-10" id="table">
      <div style="/*background:transparent !important*/" class="jumpbotron-fluid" id="colortable">
        
        <div class="row col-12">
          <%= form_tag posts_path, method: :get do%>
          <%= hidden_field_tag :direction, params[:direction]%>
          <%= hidden_field_tag :sort, params[:sort]%>
          <p>
            <%= text_field_tag :search, params[:search], size: 70, placeholder: 'Tìm kiếm sản phẩm'%>
            <%= button_tag :submit, name: nil, class: 'btn btn-danger', id: 'searchbutton' do %>
            <span class="fa fa-plus"></span> Tìm kiếm
            <% end %>
          </p>
        <% end %>
          
          <%= button_to new_post_path, method: :get, type: "button", class: "btn btn-danger", id: "importbutton" do %>
          <span class="fa fa-file-text-o"></span> Thêm hàng
          <% end %>
          
        </div>

        <div class="container-fluid" id="producttable">
          <table class="table">
            <thead>
              <tr class="table-info">
                <th>Mã hàng</th>
                <th>Ảnh sản phẩm </th>
                <th>Tên hàng</th>
                <th>Giá bán</th>
                <th>Giá vốn</th>
                <th>Tồn kho</th>
                <th>Chi tiết</th>
                <th>Sửa</th>
                <th>Xóa</th>
                <th>Thêm giỏ hàng</th>
              </tr>
            </thead>
            <tbody>
               <% @posts.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td>
                <% if (post.image.attached? == true) %>
                <%= image_tag(post.image, height: 100, width: :auto) %>
                <% else %>
                No Image attached
                <% end %>
                </td>
                <td><%= post.body %></td>
                <td><%= post.price %> VNĐ</td>
                <td><%= post.cost %> VNĐ</td>
                <td><%= post.quantity %></td>
                <td><%= button_to 'Show', post, method: :get ,class: 'btn btn-info btn-xs'%></td>
                <td><%= button_to 'Edit', edit_post_path(post), method: :get, class: 'btn btn-info btn-xs'  %></td>
                <td><%= button_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-info btn-xs' %></td>
                <td><%= button_to 'Add to Cart', line_items_path(post_id: post), remote: true, class: 'btn btn-info btn-xs'%></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

        <div class="row col-12">
        </div>
      </div>
    </div>
  </div>

<!--script type="text/javascript"></script-->
<script>
function myFunction() {
  // Declare variables
  var input, filter, ul, li, a, i, txtValue;
  input = document.getElementById('myInput');
  filter = input.value.toUpperCase();
  ul = document.getElementById("myUL");
  li = ul.getElementsByTagName('li');

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    a = li[i].getElementsByTagName("a")[0];
    txtValue = a.textContent || a.innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>
</body>
</html>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <% if @post.image.attached? == false %>
  <p>No image attached</p>
  <% else %>
  <div style="width:400px; height:auto">
  <%= image_tag(@post.image, style: 'width:100%')%>
  </div>
  <% end %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.email.split('@')[0].capitalize %>
</p>

<p>
  <strong>Price:</strong>
  <%= @post.price %> VNĐ
</p>

<p>
  <strong>Cost:</strong>
  <%= @post.cost %> VNĐ
</p>

<p>
  <strong>Quantity:</strong>
  <%= @post.quantity %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>